#!/bin/bash
#
# mod_index
#    index fab modules
#
# Neil Gershenfeld
# (c) Massachusetts Institute of Technology 2014
#
# This work may be reproduced, modified, distributed,
# performed, and displayed for any purpose, but must
# acknowledge the fab modules project. Copyright is
# retained and must be preserved. The work is provided
# as is; no warranty is provided, and users accept all 
# liability.
#

echo '<html>' > mods.html
echo '<head>' >> mods.html
echo '<meta http-equiv="Content-Type" content="text/html; charset=utf-8">' >> mods.html
echo '</head>' >> mods.html
echo '<body>' >> mods.html
echo '<a href=http://cba.mit.edu>CBA</a> ' >> mods.html
echo '<a href=http://kokompe.cba.mit.edu>fab modules</a> ' >> mods.html
echo '<a href=http://fabfoundation.org>fab labs</a><br><br>' >> mods.html
echo 'version: '`date`'<br><br>' >> mods.html
ls index.html > mods.tmp
ls mod_settings >> mods.tmp
ls mod_get >> mods.tmp
ls mod_serve >> mods.tmp
ls mod_index >> mods.tmp
ls mods/*js >> mods.tmp
ls inputs/*js >> mods.tmp
ls outputs/*js >> mods.tmp
ls processes/*js >> mods.tmp
ls mod_server/*js >> mods.tmp
ls mod_server/*py >> mods.tmp
ls templates/*html >> mods.tmp
awk '{ printf "<a href=" $0 ">" $0 "</a><br>\n" }' mods.tmp >> mods.html
#echo "<br>mod_server dependencies: <a href=http://nodejs.org/>Node.js</a> (<a href=https://github.com/joyent/node/wiki/Installing-Node.js-via-package-manager>packages</a>), <a href=https://www.npmjs.org/>npm</a>, <a href=https://www.npmjs.org/package/ws>ws</a>, <a href=https://www.npmjs.org/package/serialport>serialport</a><br>" >> mods.html
echo "mod_server dependencies: <a href=http://nodejs.org/>Node.js</a> (<a href=https://github.com/joyent/node/wiki/Installing-Node.js-via-package-manager>packages</a>), <a href=https://www.npmjs.org/>npm</a>, <a href=https://www.npmjs.org/package/ws>ws</a><br>" >> mods.html
echo "mod_serial.py dependencies: <a href=https://www.python.org/>Python</a>, <a href=http://pyserial.sourceforge.net/pyserial.html>pySerial</a>, <a href=http://www.wxpython.org/>wxPython</a><br>" >> mods.html
echo '<a href=http://requirejs.org/docs/release/2.1.15/minified/require.js>require.js</a><br/>' >> mods.html
echo '<a href=http://builds.handlebarsjs.com.s3.amazonaws.com/handlebars-v2.0.0.js>handlebars-v2.0.0.js</a><br/>' >> mods.html
echo '<br>This work may be reproduced, modified, distributed,<br>' >> mods.html
echo 'performed, and displayed for any purpose, but must<br>' >> mods.html
echo 'acknowledge the fab modules project. Copyright is<br>' >> mods.html
echo 'retained and must be preserved. The work is provided<br>' >> mods.html
echo 'as is; no warranty is provided, and users accept all<br>' >> mods.html
echo 'liability.' >> mods.html
echo "#!/bin/bash" > mod_get
awk '{ printf "wget -x http://fabmodules.org/" $0 "\n" }' mods.tmp >> mod_get
echo "wget -x http://requirejs.org/docs/release/2.1.15/minified/require.js -O fabmodules.org/require.js" >> mod_get
echo "wget -x http://builds.handlebarsjs.com.s3.amazonaws.com/handlebars-v2.0.0.js -O fabmodules.org/handlebars-v2.0.0.js" >> mod_get
echo "cd fabmodules.org/mod_server" >> mod_get
echo "npm install ws" >> mod_get
rm mods.tmp

